[package]
name = "Assignment_Rust_Data_Loader"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = "2.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

